import { test, expect } from '@playwright/test';

// notes 
// bolow code has been generated by codegen - test code generator
// below command used to run the script
// npx playwright codegen https://www.saucedemo.com/

test('test', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.getByText('Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitc').click({
    clickCount: 3
  });
  await page.locator('body').press('Control+c');
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await page.locator('form').click();
  await page.locator('[data-test="login-button"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click();
  await page.locator('a').filter({ hasText: '1' }).click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill('fasdf');
  await page.locator('[data-test="lastName"]').fill('d');
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').fill('dfsf');
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill('fdsf');
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="finish"]').click();
  await page.locator('[data-test="back-to-products"]').click();
  await page.locator('div').filter({ hasText: /^Open Menu$/ }).nth(1).click();
  await page.getByRole('link', { name: 'Logout' }).click();
});